# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [6]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [7]:
city_data_df = pd.read_csv("../WeatherPy/output_data/cities_1.csv")
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,kapaa,22.0752,-159.3190,26.99,77,40,6.17,US,1651608887
1,1,barrow,71.2906,-156.7887,-5.99,86,100,5.14,US,1651608707
2,2,busselton,-33.6500,115.3333,13.33,68,84,4.85,AU,1651608889
3,3,mar del plata,-38.0023,-57.5575,16.08,59,0,6.17,AR,1651608890
4,4,vaini,-21.2000,-175.2000,23.09,88,20,2.57,TO,1651608890

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [15]:
# Configure gmaps with API key.
gmaps.configure(api_key=g_key)

#  Humidity to store

humidity = city_data_df["Humidity"]

# Store 'Latitude' and 'Longitude' into  locations. 
locations = city_data_df[["Lat", "Lng"]]

# Create a humidity Heatmap layer
# Plot Heatmap
fig = gmaps.figure(center = [0,0] ,zoom_level = 2)
# Create and add heat layer 
heat_layer = gmaps.heatmap_layer(locations, weights=humidity,
                               dissipating=False, max_intensity=200,
                               point_radius = 4)
fig.add_layer(heat_layer)
#Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [12]:
# Narrow down the cities to fit weather conditions and Drop any rows will null values.
narrow_city_df = city_data_df.loc[(city_data_df["Max Temp"] < 27) & (city_data_df["Max Temp"] > 21) \
                                    & (city_data_df["Wind Speed"] < 4.5) \
                                    & (city_data_df["Cloudiness"] == 0)].dropna()
narrow_city_df

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
32,32,prado,-17.3411,-39.2208,25.18,73,0,3.11,BR,1651608908
68,68,sao filipe,14.8961,-24.4956,22.95,76,0,4.32,CV,1651608933
126,126,kingman,35.1894,-114.0530,23.96,8,0,4.12,US,1651608887
135,135,caravelas,-17.7125,-39.2481,25.08,72,0,2.54,BR,1651608969
157,157,zhuhai,22.2769,113.5678,22.84,68,0,3.09,CN,1651608986
210,210,catamarca,-28.4696,-65.7852,24.32,31,0,0.89,AR,1651609019
233,233,santiago del estero,-27.7951,-64.2615,21.52,31,0,1.49,AR,1651608787
278,278,madimba,-10.4000,40.3333,23.61,86,0,4.17,TZ,1651609057
346,346,tucuman,-26.8241,-65.2226,22.00,40,0,2.06,AR,1651609092
353,353,karratha,-20.7377,116.8463,26.23,58,0,1.66,AU,1651609095
487,487,pisco,-13.7000,-76.2167,23.03,60,0,3.09,PE,1651609169

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [14]:
# Store into variable named hotel_df.
hotel_df = narrow_city_df

# parameters dictionary to update when iterating
params = {"radius": 5000,
    "types": "lodging",
    "key": g_key
}


for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # assemble url and make API request
    print(f"Retrieving Results for Index {index}: {row['City']}.")
    response = requests.get(base_url, params=params).json()
    # print(json.dumps(response, indent=4, sort_keys=True))
    
    # extract results
    results = response['results']
    
    try:
        print(f"Closest hotel is {results[0]['name']}.")
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")

Retrieving Results for Index 32: prado.
Closest hotel is INN CORNER RIVER - PRADO - BAHIA - HOUSING AND HOTEL.
------------
Retrieving Results for Index 68: sao filipe.
Closest hotel is Hotel Xaguate.
------------
Retrieving Results for Index 126: kingman.
Closest hotel is Rodeway Inn Kingman Route 66.
------------
Retrieving Results for Index 135: caravelas.
Closest hotel is Pousada dos Navegantes.
------------
Retrieving Results for Index 157: zhuhai.
Closest hotel is 珠海粤财假日酒店.
------------
Retrieving Results for Index 210: catamarca.
Closest hotel is Amerian Catamarca Park Hotel.
------------
Retrieving Results for Index 233: santiago del estero.
Closest hotel is Apartamentos Castelli 90.
------------
Retrieving Results for Index 278: madimba.
Missing field/result... skipping.
------------
Retrieving Results for Index 346: tucuman.
Closest hotel is Dallas Hotel Tucuman.
------------
Retrieving Results for Index 353: karratha.
Closest hotel is ibis Styles Karratha.
------------
Retrieving Results for Index 487: pisco.
Closest hotel is Hotel San Isidro Oficial.
------------

In [18]:
hotel_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
32,32,prado,-17.3411,-39.2208,25.18,73,0,3.11,BR,1651608908,INN CORNER RIVER - PRADO - BAHIA - HOUSING AND...
68,68,sao filipe,14.8961,-24.4956,22.95,76,0,4.32,CV,1651608933,Hotel Xaguate
126,126,kingman,35.1894,-114.0530,23.96,8,0,4.12,US,1651608887,Rodeway Inn Kingman Route 66
135,135,caravelas,-17.7125,-39.2481,25.08,72,0,2.54,BR,1651608969,Pousada dos Navegantes
157,157,zhuhai,22.2769,113.5678,22.84,68,0,3.09,CN,1651608986,珠海粤财假日酒店

In [23]:
hotel_df.shape

(11, 11)

In [20]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [22]:
# Add marker layer ontop of heat map
hotel_layer = gmaps.symbol_layer(
    locations, fill_color='rgba(0, 150, 0, 0.4)',
    stroke_color='rgba(0, 0, 150, 0.4)', scale=2,
    info_box_content=hotel_info)

# Display figure
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
fig.add_layer(hotel_layer)

fig

Figure(layout=FigureLayout(height='420px'))